FROM alpine:3

RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

RUN apk add --no-cache \
  ruby \
  bash \
  vim \
  elinks \
  neomutt@testing \
  abook \
  git \
  curl


