#!/usr/bin/env bash
set -eo pipefail
[[ "$TRACE" ]] && set -x

out() {
  echo "** $@"
}

run_escape_to() {
  exec "$@"
}

configure_mutt() {
  local mayaml_file=$1
  mkdir -p ~/.mutt/accounts
  mayaml-mutt-init ${mayaml_file} ~/.mutt/init.muttrc
  mayaml-mutt-creds ${mayaml_file} ~/.mutt/accounts
}

run_mutt() {
  local host_dir="$1"
  cd ${host_dir} && neomutt
}

main() {
  local mutt_host_dir=${MUTT_HOST_DIR:-/mnt/host}
  local mayaml_file=${MAYAML_FILE}

  case "$1" in
  escto)
    shift; run_escape_to "$@";;
  *)
    configure_mutt "$mayaml_file"
    run_mutt "$mutt_host_dir"
  esac
}

main "$@"
